export type AssessmentStatus = 'DRAFT' | 'EVALUATING' | 'READY' | 'NOT_READY' | 'INCOMPLETE' | 'EXPIRED' | 'CONSUMED' | 'CANCELLED' | string;

export interface ReadinessCheck { readonly status: string; readonly reason?: string | null; readonly evaluatedAt?: string | null; }
export interface PersonnelCandidate { readonly id: string; readonly name: string; readonly role: string; readonly region?: string; readonly availability: string; readonly eligibility: string; readonly conflict?: string | null; readonly reason?: string | null; }
export interface UavCandidate { readonly id: string; readonly code: string; readonly name?: string; readonly operationalStatus: string; readonly technicalHealth: string; readonly lastInspection?: string | null; readonly validUntil?: string | null; readonly eligibility: string; readonly conflict?: string | null; }
export interface TechnicalMetric { readonly subsystem: string; readonly metric: string; readonly value: string | number; readonly unit?: string | null; readonly required?: string | boolean | null; readonly severity?: string | null; readonly passed?: boolean | null; }
export interface PreMissionAssessment { readonly id: string; readonly assessmentCode: string; readonly regionName: string; readonly lineName?: string | null; readonly assetCount: number; readonly plannedStart: string; readonly plannedEnd: string; readonly site: ReadinessCheck; readonly personnel: ReadinessCheck; readonly uav: ReadinessCheck; readonly technical: ReadinessCheck; readonly status: AssessmentStatus; readonly validUntil?: string | null; readonly createdBy?: string | null; readonly updatedAt?: string | null; readonly consumedMissionId?: string | null; readonly personnelCandidates: readonly PersonnelCandidate[]; readonly uavCandidates: readonly UavCandidate[]; readonly technicalMetrics: readonly TechnicalMetric[]; readonly scopeAssetIds: readonly string[]; readonly scopeGeometry?: unknown; }
export interface AssessmentPage { readonly items: readonly PreMissionAssessment[]; readonly page: number; readonly pageSize: number; readonly totalCount: number; readonly totalPages: number; }
export interface AssessmentCreateRequest { readonly regionId: string; readonly scopeAssetIds: readonly string[]; readonly plannedStart: string; readonly plannedEnd: string; readonly scopeGeometry?: unknown; }
